substitutions:
  device_name: "arlec_mod_12w"
  friendly_name: "Arlec CCT ESPmod"

esphome:
  name: ${device_name}
  comment: ${friendly_name}
  platform: ESP8266
  board: esp12e
  esp8266_restore_from_flash: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: ${device_name}
    password: !secret wifi_password

captive_portal:

# Enable web server
web_server:
  port: 80
  auth:
    username: !secret web_server_user
    password: !secret web_server_password

logger:

api:
  encryption:
    key: !secret hass_key

ota:
  password: !secret ota_password

output:
  - platform: esp8266_pwm
    id: cw_color_temp
    pin: GPIO12
  - platform: esp8266_pwm
    id: ww_color_temp
    pin: GPIO14

light:
  - platform: cwww
    name: ${friendly_name}
    cold_white: cw_color_temp
    warm_white: ww_color_temp
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    restore_mode: RESTORE_AND_ON
    effects:
      - pulse:
      - strobe:
