esphome:
  name: dimini_dallas
  platform: ESP8266
  board: d1_mini

time:
  - platform: sntp
    id: sntp_time

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on
  reboot_timeout: 0s
  power_save_mode: high
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Espiggy Fallback Hotspot"
    password: !secret fallback_password
  
captive_portal:

# Enable web server
web_server:
  port: 80
  auth:
    username: !secret web_server_user
    password: !secret web_server_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret hass_password

ota:
  password: !secret ota_password

dallas:
  - pin: D5

sensor:
  - platform: dallas
    address: 0xD9031553B28EFF28
    name: "Temperature outside"
