esphome:
  name: d1mini_ldr
  platform: ESP8266
  board: d1_mini

time:
  - platform: sntp
    id: sntp_time

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on
  reboot_timeout: 0s
  power_save_mode: high
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

# Enable web server
web_server:
  port: 80
  auth:
    username: !secret web_server_user
    password: !secret web_server_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret hass_password

ota:
  password: !secret ota_password

sensor:
  - platform: pulse_meter
    pin: D5
    unit_of_measurement: 'kW'
    name: 'Power Meter'
    filters:
      - multiply: 0.06
    internal_filter: 5ms
    total:
      name: "Power Meter Total"
      unit_of_measurement: "kWh"
      accuracy_decimals: 0
      filters:
        - multiply: 0.001
