esphome:
  name: esp12_rgb
  platform: esp8266
  board: esp12e
    #  board_build.f_cpu: 160000000L

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "esp12-rgb Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

# Enable web server
web_server:
  port: 80
  auth:
    username: !secret web_server_user
    password: !secret web_server_password
      
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret hass_password

ota:
  password: !secret hass_password

light:
  - platform: rgb
    name: "Fibre light"
    red: output_red
    green: output_green
    blue: output_blue
    effects:
      - pulse:
      - random:
      - strobe:

output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO0
    inverted: true
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO5
    inverted: true
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO01
    inverted: true
