esphome:
  name: esp32_touch
  platform: ESP32
  board: m5stack-grey

# time:
#   - platform: sntp
#     id: sntp_time

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on
  reboot_timeout: 0s
  power_save_mode: high
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} Fallback Hotspot"
    password: !secret fallback_password

# Enable Home Assistant API
api:
  encryption:
    key: !secret hass_key

ota:
  password: !secret hass_password

esp32_touch:
  setup_mode: False

binary_sensor:
  - platform: esp32_touch
    name: "ESP32 Touch Pad GPIO27"
    pin: GPIO27
    threshold: 50
    on_press:
      - homeassistant.service:
          service: esphome.esp12_player_dfplayer_play
          data:
            file: "12"
# # Example configuration entry
# deep_sleep:
#   run_duration: 10s
#   wakeup_pin: GPIO027
#   wakeup_pin_mode: INVERT_WAKEUP

# captive_portal:

# # Enable web server
# web_server:
#   port: 80
#   auth:
#     username: !secret web_server_user
#     password: !secret web_server_password

# # Enable logging
# logger:

# sensor:
#   - platform: wifi_signal
#     name: "WiFi Signal Sensor"
#     update_interval: 10s

