esphome:
  name: espiggy
  platform: ESP8266
  board: esp01_1m

i2c:
  scan: True
  id: bus_a

time:
  - platform: sntp
    id: sntp_time

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on
  reboot_timeout: 0s
  power_save_mode: high
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

# Enable web server
web_server:
  port: 80
  auth:
    username: !secret web_server_user
    password: !secret web_server_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret hass_key

ota:
  password: !secret ota_password

sensor:
  - platform: bmp280
    address: 0x76
    temperature:
      name: "TV Temperature"
      oversampling: 16x
    pressure:
      name: "TV Pressure"
    update_interval: 60s
  - platform: adc
    pin: A0
    name: "TV Brightness"
    unit_of_measurement: "%"
    accuracy_decimals: 0
    icon: "mdi:brightness-percent"
    update_interval: 60s
    filters:
      multiply:
        100

        #light:
        #  - platform: rgb
        #    name: "TV Room LED"
        #    red: output_component1
        #    green: output_component2
        #    blue: output_component3
        #
        #output:
        #  - platform: esp8266_pwm
        #    id: output_component1
        #    pin: GPIO15
        #
        #  - platform: esp8266_pwm
        #    id: output_component2
        #    pin: GPIO12
        #
        #  - platform: esp8266_pwm
        #    id: output_component3
        #    pin: GPIO13
        #
