esphome:
  name: guition-round
  friendly_name: Guition Round
  platformio_options:
    friendly_name: JC3636W518CN
    board_build.flash_mode: dio
    board_build.f_flash: 80000000L
    board_build.f_cpu: 240000000L

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
    #speed: 120MHz

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret hass_key

ota:
  - platform: esphome
    password: !secret hass_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Guition-360X360-Jc3636W518"
    password: !secret fallback_password

captive_portal:

i2s_audio:
  - id: i2s_in
    i2s_lrclk_pin: GPIO45
    i2s_bclk_pin: GPIO42
  - id: i2s_out
    i2s_lrclk_pin: GPIO16
    i2s_bclk_pin: GPIO18
    i2s_mclk_pin: GPIO21

microphone:
  - platform: i2s_audio
    id: i2s_microphone
    i2s_audio_id: i2s_in
    i2s_din_pin: GPIO46
    adc_type: external
    pdm: false
    channel: left
    sample_rate: 16000
    bits_per_sample: 32bit
speaker:
  - platform: i2s_audio
    id: i2s_speaker
    i2s_audio_id: i2s_out
    i2s_dout_pin: GPIO17
    dac_type: external
    channel: stereo
    # i2s_comm_fmt: i2s_msb
voice_assistant:
  id: va
  microphone: i2s_microphone
  speaker: i2s_speaker
  use_wake_word: false
  noise_suppression_level: 2 #4
  auto_gain: 31dBFS # 31dBFS
  volume_multiplier: 2 # 8.0

binary_sensor:
  - platform: gpio
    name: Click_to_Converse
    id: Click_to_Converse
    pin:
      number: 0  
    on_press:
      - if:
          condition: 
            - voice_assistant.is_running
          then:
            - voice_assistant.stop:
          else:
            - voice_assistant.start:

  - platform: homeassistant
    id: is_muted
    entity_id: media_player.lg_c4
    attribute: is_volume_muted
    name: "Media Player Muted"
    
spi:
  id: display_qspi
  type: quad
  clk_pin: 9
  data_pins: [11, 12, 13, 14]

i2c:
  sda: 7
  scl: 8
  id: touchscreen_bus

display:
  - platform: mipi_spi
    model: JC3636W518
    data_rate: 40MHz
    id: main_display
    spi_id: display_qspi
    color_order: rgb
    invert_colors: true
    dimensions:
      height: 360
      width: 360
    cs_pin: 10
    reset_pin: GPIO47
    auto_clear_enabled: false #set to false for LVGL

lvgl:
  #full_refresh: true # redraw whole display every time so very slow
  displays:
    - main_display
  touchscreens:
    - my_touchscreen
  theme:
    bar:
      radius: 0
      indicator:
        radius: 0
        arc_color: red

  pages:
    - id: canvas_1
      bg_color: blue
      widgets:
        - arc:
            id: volume_arc
            x: 10
            y: 10
            width: 340
            height: 340
            value: 80
            min_value: 0
            max_value: 100
            adjustable: true
            start_angle: 0
            end_angle: 350
            rotation: 0
            change_rate: 360
            arc_color: 0x000000
            indicator:
              arc_color: 0x555555
              arc_opa: 50%
              arc_rounded: true
            knob:
              bg_color: 0x555555
              radius: 20
            on_change:
              - lvgl.label.update:
                  id: volume_label
                  text: !lambda |-
                    static char buf[20];
                    sprintf(buf, "Volume: %.0f", x);
                    return buf;
              # - light.turn_on:
              #     id: back_light
              #     brightness: !lambda 'return x/100;'
              # - homeassistant.service:
              #     service: homeassistant.turn_on
              #     data:
              #       entity_id: light.esp32rgb_living_room_lights
              #       brightness_pct: !lambda 'return x;'
              - homeassistant.service:
                  service: media_player.volume_set
                  data:
                    entity_id: media_player.lg_c4
                    volume_level: !lambda 'return x/100;'
        - label:
            id: volume_label
            text_font: gotham_rounded_bold_28
            text_align: center
            x: 90
            y: 165
            width: 180
            height: 30
            text: "Volume: 80%"
            on_click:
              if:
                condition:
                  binary_sensor.is_on: is_muted
                then:
                  - homeassistant.service:
                      service: media_player.volume_mute
                      data:
                        entity_id: media_player.lg_c4
                        is_volume_muted: "false"
                else:
                  - homeassistant.service:
                      service: media_player.volume_mute
                      data:
                        entity_id: media_player.lg_c4
                        is_volume_muted: "true"
        - label:
            id: amp_label
            text_font: gotham_rounded_bold_28
            text_align: center
            x: 120
            y: 265
            width: 120
            height: 30
            text: "Amplifier"
            on_click:
              - homeassistant.service:
                  service: switch.toggle
                  data:
                    entity_id: switch.smartplug1
output:
  - platform: ledc
    pin: GPIO15
    id: backlight

font:
  - file: "fonts/Gotham-Rounded-Bold.ttf"
    id: gotham_rounded_bold_28
    size: 28

switch:
  - platform: gpio
    pin: GPIO48
    id: mute
    name: "mute"
    restore_mode: ALWAYS_ON

light:
  - platform: monochromatic
    output: backlight
    id: back_light
    name: "backlight Light" 
    restore_mode: ALWAYS_ON

touchscreen:
  platform: cst816
  id: my_touchscreen
  interrupt_pin: GPIO41
  reset_pin: GPIO40
  display: main_display
  i2c_id: touchscreen_bus
  update_interval: 50ms

