# NOTE: This is currently not used because IR support has not
# yet been enabled in LibreTuya
substitutions:
  device_name: "irblaster"
  friendly_name: "IR Blaster"

esphome:
  name: ${device_name}
  comment: ${friendly_name}
  platform: bk72xx

    #libretuya:
  board: generic-bk7231t-qfn32-tuya
    #framework:
    #version: dev
  # verbose/trace/debug/info/warn/error/fatal
  #loglevel: debug
  # suppress chip's SDK log messages
  # (same as LT_UART_SILENT_ALL above)
  #sdk_silent: true
  # disable SWD/JTAG so that all GPIOs can be used
  # set to false if you want to attach a debugger
  #gpio_recover: true

# Enable Home Assistant API
api:
  encryption:
    key: !secret hass_key

ota:
  platform: esphome
  password: !secret hass_password

web_server:
  port: 80
  auth:
    username: !secret web_server_user
    password: !secret web_server_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.2.50
    gateway: 192.168.2.1
    subnet: 255.255.255.0

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: ${device_name}
    password: !secret wifi_password

captive_portal:

logger:
# remote_receiver:
#   pin: GPIO8
#   dump: samsung
#   buffer_size: 1k

# remote_transmitter:
#   pin: GPIO26
#   carrier_duty_percent: 50%

# # Individual switches
# switch:
#   - platform: template
#     name: "Panasonic TV Off"
#     turn_on_action:
#       remote_transmitter.transmit_panasonic:
#         address: 0x4004
#         command: 0x100BCBD
