esphome:
  name: nodemcu2
  platform: ESP8266
  board: nodemcu

i2c:
  scan: True
  id: bus_a

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Espiggy Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

# Enable web server
web_server:
  port: 80

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret hass_key
ota:
  password: !secret ota_password

sensor:
  - platform: adc
    pin: A0
    name: "TV Brightness"
    unit_of_measurement: "%"
    accuracy_decimals: 0
    icon: "mdi:brightness-percent"
    update_interval: 1s
    filters:
      - calibrate_linear:
          - 0.0 -> 0.0
          - 1.0 -> 100.0
