substitutions:
  device_name: "s20th"
  friendly_name: "Garage"
  sonoff_type: "TH10"

time:
  - platform: sntp
    id: sntp_time

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on
  reboot_timeout: 0s
  power_save_mode: high
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "S20 Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

# Enable web server
web_server:
  port: 80
  auth:
    username: !secret web_server_user
    password: !secret web_server_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret hass_key

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp8285

ota:
  platform: esphome
  password: !secret ota_password

sensor:
  - platform: dht
    model: dht22
    pin: GPIO14
    temperature:
      name: ${friendly_name} Temperature
    humidity:
      name: ${friendly_name} Humidity
binary_sensor:
  - platform: status
    name: ${friendly_name} ${sonoff_type} Status
switch:
  - platform: restart
    name: ${friendly_name} ${sonoff_type} Restart
  - platform: gpio
    name: ${friendly_name} ${sonoff_type}
    pin: GPIO12
    id: relay
    #restore_mode: ALWAYS_OFF
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} ${sonoff_type} IP
    ssid:
      name: ${friendly_name} ${sonoff_type} SSID
    bssid:
      name: ${friendly_name} ${sonoff_type} BSSID
