# Substitution variables used through the codebase
substitutions:
  icon_font: mdi_icons_40
  text_font: nunito_24
  text_color: white
  bg_color: black
  button_on_color: "ep_orange"
  button_off_color: "very_dark_gray"
  icon_on_color: "yellow"
  icon_off_color: "gray"
  label_on_color: "white"
  label_off_color: "gray"
  button_text_color: "white"
  button_height_single: '109px'
  button_height_double: '228px'
  button_width: '150px'
  touchscreen_idle_timeout: "30s"
  touchscreen_daytime_brightness: "100%"
  touchscreen_nighttime_brightness: "50%"
  # Boot screen configuration
  boot_screen_delay: 60s

  # LCD backlight modes - Code in backlight.yaml
  # Day mode is set to Sunrise
  # Evening mode is set to sunset
  # Set Night mode  at Midnight here
  screen_night_hour: '0'
  screen_night_minute: '0'

  # Screen Size
  screen_height: '320'
  screen_width: '480'
  byte_order: big_endian

esphome:
  name: sdl-weather
  friendly_name: SDL Weather
#   on_boot:
#     - priority: 400
#       then:
#         - script.execute: update_loading_page

logger:
  level: debug

api:
#   on_client_connected:
#     - script.execute: time_update
  encryption:
    key: !secret hass_key

time:
  - platform: homeassistant
    id: system_time

network:

packages:
  # Generic configuration for ESP32 screens
  # All the colors
  colors: !include esphome-modular-lvgl-buttons/common/color.yaml
  # Fonts you need
  fonts: !include esphome-modular-lvgl-buttons/common/fonts.yaml
  # 1000s of glyphs
  glyphs: !include esphome-modular-lvgl-buttons/common/mdi_glyph_substitutions.yaml
  # Some basic sensors
  #   sensors: !include esphome-modular-lvgl-buttons/sensors/sensors_base-SDL.yaml
  # Styles + Themes
  # theme_style: !include esphome-modular-lvgl-buttons/common/theme_style_debug.yaml
#   theme_style: !include esphome-modular-lvgl-buttons/common/theme_style.yaml

  # Harware description file
  hardware: !include esphome-modular-lvgl-buttons/hardware/sunton-esp32-3248s035.yaml
  
# Basic boot screen with ESPHome logo and device diagnostic info
#   loading_screen: !include esphome-modular-lvgl-buttons/pages/loading_480px.yaml
#   info_screen: !include esphome-modular-lvgl-buttons/pages/info.yaml

  # Weather packages
  # Display weather forecast using direct HA action (no template sensor needed!)
  # Icons are included automatically in the action file
  weather_forecast_80: !include
    file: esphome-modular-lvgl-buttons/weather_homeassistant/weather_forecast_action.yaml
    vars:
      size: 80
      weather_entity: weather.home
  # Get todays weather and display it (icons included automatically)
  weather_today_200: !include
    file: esphome-modular-lvgl-buttons/weather_homeassistant/weather_today.yaml
    vars:
      size: 100
      weather_entity: weather.home
      weather_summary: sensor.home_hourly_summary

# Styles for Weather forecast
.forecast_styles:
    - &forecast_obj_base
      height: SIZE_CONTENT
      width: SIZE_CONTENT
      bg_color: gray50
      radius: 3
      pad_top: 2
      pad_bottom: 2
      layout:
        type: flex
        flex_flow: COLUMN
        flex_align_cross: center
        flex_align_track: center
        pad_column: 0
        pad_row: 2

    - &forecast_label_base
      text_font: nunito_24
      height: SIZE_CONTENT

    - &forecast_label_base_lo
      height: SIZE_CONTENT
      text_font: nunito_20
      text_color: dodgerblue

    - &forecast_image_base
      height: SIZE_CONTENT

# script:
#   - id: time_update
#     then:
#       - lvgl.label.update:
#           id: current_time
#           text: !lambda 'return id(system_time).now().strftime("%l:%M");'  # 12-hour format, no am/pm
#       - lvgl.label.update:
#           id: month_day
#           text: !lambda |- # Month Day
#             auto time = id(system_time).now();
#             int day = time.day_of_month;
#             char strftime_buf[64];
#             snprintf(strftime_buf, sizeof(strftime_buf), "%s %d", time.strftime("%B").c_str(), day);
#             return {strftime_buf};

lvgl:
  pages:
    - id: main_page
      layout: 4x4
    #   styles: page_style
      <<: !include esphome-modular-lvgl-buttons/widgets/swipe_navigation.yaml
      bg_color: White
      widgets:
          - container:
              grid_cell_x_align: stretch
              grid_cell_y_align: stretch
              grid_cell_row_pos: 0
              grid_cell_column_pos: 0
              grid_cell_row_span: 1
              grid_cell_column_span: 2
              # outline_width: 1   # debug code - This is for visualizing boundries remove for production
              # outline_color: red # debug code - This is for visualizing boundries remove for production
              widgets:
                - label:
                    text: "12:00"
                    id: current_time
                    align: top_mid
                    text_align: center
                    text_font: nunito_48
                - label:
                    text: "September 19"
                    id: month_day
                    align: bottom_mid
                    text_font: nunito_20
                    text_align: center

          - container:
              grid_cell_x_align: stretch
              grid_cell_y_align: stretch
              grid_cell_row_pos: 1
              grid_cell_column_pos: 0
              grid_cell_row_span: 1
              grid_cell_column_span: 1
              # outline_width: 1   # debug code - This is for visualizing boundries remove for production
              # outline_color: red # debug code - This is for visualizing boundries remove for production
              widgets:
                - label:
                    text: "---°"
                    id: weather_temperature_today
                    align: center
                    text_align: center
                    text_font: nunito_48

          - container:
              grid_cell_x_align: stretch
              grid_cell_y_align: stretch
              grid_cell_row_pos: 1
              grid_cell_column_pos: 1
              grid_cell_row_span: 1
              grid_cell_column_span: 1
              # outline_width: 1   # debug code - This is for visualizing boundries remove for production
              # outline_color: red # debug code - This is for visualizing boundries remove for production
              widgets:
                - image:
                    src: unknown_100
                    id: weather_condition_icon
                    align: center
 
          - container:
              grid_cell_x_align: stretch
              grid_cell_y_align: stretch
              grid_cell_row_pos: 1
              grid_cell_column_pos: 2
              grid_cell_row_span: 1
              grid_cell_column_span: 2
              # outline_width: 1   # debug code - This is for visualizing boundries remove for production
              # outline_color: red # debug code - This is for visualizing boundries remove for production
              widgets:
                - label:
                    text: "Loading..."
                    id: weather_summary_today
                    text_font: nunito_24
                    long_mode: wrap
                    width: 100%

          - container:
              grid_cell_x_align: stretch
              grid_cell_y_align: stretch
              grid_cell_row_pos: 2
              grid_cell_column_pos: 0
              grid_cell_row_span: 2
              grid_cell_column_span: 4
              # outline_width: 1   # debug code - This is for visualizing boundries remove for production
              # outline_color: red # debug code - This is for visualizing boundries remove for production
              layout: 1x4
              widgets:
                  - obj:
                      <<: *forecast_obj_base
                      grid_cell_row_pos: 0
                      grid_cell_column_pos: 0
                      widgets:
                          - label:
                              id: forecast_day_0
                              <<: *forecast_label_base
                              text: ???
                          - image:
                              id: forecast_condition_icon_0
                              <<: *forecast_label_base
                              src: unknown_80
                          - label:
                              id: forecast_temperature_hi_0
                              <<: *forecast_label_base
                              text: "---°"
                          - label:
                              id: forecast_temperature_lo_0
                              <<: *forecast_label_base_lo
                              text: "---°"
                  - obj:
                      <<: *forecast_obj_base
                      grid_cell_row_pos: 0
                      grid_cell_column_pos: 1
                      widgets:
                          - label:
                              id: forecast_day_1
                              <<: *forecast_label_base
                              text: ???
                          - image:
                              id: forecast_condition_icon_1
                              <<: *forecast_label_base
                              src: unknown_80
                          - label:
                              id: forecast_temperature_hi_1
                              <<: *forecast_label_base
                              text: "---°"
                          - label:
                              id: forecast_temperature_lo_1
                              <<: *forecast_label_base_lo
                              text: "---°"
                  - obj:
                      <<: *forecast_obj_base
                      grid_cell_row_pos: 0
                      grid_cell_column_pos: 2
                      widgets:
                          - label:
                              id: forecast_day_2
                              <<: *forecast_label_base
                              text: ???
                          - image:
                              id: forecast_condition_icon_2
                              <<: *forecast_label_base
                              src: unknown_80
                          - label:
                              id: forecast_temperature_hi_2
                              <<: *forecast_label_base
                              text: "---°"
                          - label:
                              id: forecast_temperature_lo_2
                              <<: *forecast_label_base_lo
                              text: "---°"
                  - obj:
                      <<: *forecast_obj_base
                      grid_cell_row_pos: 0
                      grid_cell_column_pos: 3
                      widgets:
                          - label:
                              id: forecast_day_3
                              <<: *forecast_label_base
                              text: ???
                          - image:
                              id: forecast_condition_icon_3
                              <<: *forecast_label_base
                              src: unknown_80
                          - label:
                              id: forecast_temperature_hi_3
                              <<: *forecast_label_base
                              text: "---°"
                          - label:
                              id: forecast_temperature_lo_3
                              <<: *forecast_label_base_lo
                              text: "---°"



